name: Test and Deploy

on:
  push:
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - .github/workflows/test-and-deploy.yml
  pull_request:
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - .github/workflows/test-and-deploy.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v20.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.0

      - name: Install dependencies
        run: |
          npm install --global pnpm
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/jaku-bb/bot:latest
          docker push ghcr.io/jaku-bb/bot:latest
